project:
  type: website

website:
  title: "Beatson-CompBio.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - people.qmd

format:
  html:
    theme: journal
    css: styles.css
    toc: true
    page-layout: full

editor: visual

